### PR TITLE
Standard

### PR DESCRIPTION
**Pull request by brettz9**
- Linting: Applies `standard` eslint config
- Linting: Adds additional rules, `no-var`, `prefer-destructuring`, `object-shorthand`
- Refactoring: Use `includes` over `indexOf` where possible (`prefer-includes` from unicorn config without adding it to the config)

In addition to `standard` I added a small handful of rules I find to make the code a lot less cluttered and clear. Let me know if you want any changed or removed.

Btw, some people also add back the semi-colons which `standard` omits. I can insist on them being present if you prefer.

### CODE REVIEW

**Comment by brettz9** [comment]
Apologies, I hadn't noticed the failing Travis build. I've updated (adding missing devDeps) and see it is now passing.

**Comment by onechiporenko** [comment]
Thanks @brettz9 !

**Comment by brettz9** [comment]
And sorry to trouble, but if you wouldn't mind another release, that'd be great too, as I could take advantage of the new config and rule... Thanks!

**Comment by onechiporenko** [comment]
+ eslint-plugin-mocha-cleanup@1.8.0

**Comment by brettz9** [comment]
Sweet, thanks!

**Pull request merged**
