### PR TITLE
Configs

### LINKED ISSUE #8: Add recommended config
Hi,

It'd be nice to avoid needing to add to `plugins` and manually adding best practice rules (instead just needing to add `extends: ['plugin:mocha-cleanup/recommended']` and enabling/overriding any additional rules desired). Would you be open to a recommended config?

I wouldn't think it should have specific assert limits or complexity limits by default as I'd think these would vary more by project, but some rules like `no-empty-title`, just seem good to get by default.

I could offer a PR if this were desired. Thanks!

### PR DESCRIPTION
**Pull request by brettz9**
Builds on #10. Fixes #8.

- Enhancement: Add `recommended` and `recommended-no-limits` configs
- Docs: Indicate defaults for `asserts-limit` and `complexity-it`

### CODE REVIEW

**Comment by onechiporenko** [comment]
Thanks @brettz9!

**Comment by brettz9** [comment]
Thanks for the merge, @onechiporenko ! Please let me know when you may be ready for a new npm release. If you like, I can let you know how the configs are working.

**Comment by onechiporenko** [comment]
I'm going to publish new version tomorrow. I didn't get what is `.ncurc.js`?

**Comment by brettz9** [comment]
If you use https://github.com/tjunnone/npm-check-updates , it will customize how the auto-updating works.

This is a very useful global utility to install as it can automatically update the deps. and devDeps within in `package.json`, but the config file is sometimes necessary to prevent accidentally updating peerDeps (if one wants to keep supporting older versions in one's peerDeps).

By the way, just FYI on another topic...as I noticed you have a couple `expect`-related rules, thought you might like to know there are a couple other plugins now which handle such rules:

- https://github.com/Turbo87/eslint-plugin-chai-expect
- https://github.com/ihordiachenko/eslint-plugin-chai-friendly/
- https://github.com/gavinaiken/eslint-plugin-chai-expect-keywords

**Comment by onechiporenko** [comment]
Thanks for clarifications @brettz9 :)
I thought that `eslint-plugin-mocha-cleanup` is pretty "dead" for community and almost not usable. I'm pleasantly surprised that I'm wrong.
Thanks for links. Some of them are new for me.

**Comment by brettz9** [comment]
Looks pretty usable to me (I tend to introduce myself to packages by updating and poking around like this). It may help get new usage if there are more recent updates.

Do you still use it in your own work?

**Comment by onechiporenko** [comment]
Currently I use it only for some pet-projects.

**Comment by brettz9** [comment]
I've added your project to svgedit and to a smaller project (a node-login fork) and seems to be working quite well.

I had to disable `mocha-cleanup/invalid-assertions` where using Cypess, as it has its own [`should` method](https://docs.cypress.io/api/commands/should.html). Maybe an option to disable the raw checks would be helpful here.

Also, I think it'd be nice to have an option for `mocha-cleanup/no-expressions-in-assertions` to only report if there is a better suggestion, e.g., to report such as "`strictEqual` should be used." while having an option not to report the more generic "Expression should not be used here". I want to use a more semantic option where available, but am too lazy (or see less benefit) to refactor things like this:

```js
assert.equal(n && n.value, 5);
```

**Comment by brettz9** [comment]
Btw, if I get around to doing some, are you ok with ES6 refactoring now that `engines` is bumped to Node >= 8 (e.g., destructuring, preferring `const` or if necessary `let`, etc.)?

**Comment by onechiporenko** [comment]
@brettz9 sure I'm ok with refactoring. Thanks for your participation!

**Comment by brettz9** [comment]
Re: the order, it's no worry if you were ok with the changes.

As far as any refactoring, I could either adopt a stricter linting config (e.g., "standard" or my own config which extends "standard" to include some other linting tools like "unicorn"), or I could just target a few changes like "prefer-const" in case you are hesitant to make stylistic changes (though even with the configs, one could override rules such as `quotes` or `quote-props` to your liking).

**Comment by onechiporenko** [comment]
I think "standard" would be good.

**Pull request merged**
